# Generated by Django 4.2 on 2024-03-05 12:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0004_delete_chargepointerror'),
        ('cdrs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('country_code', models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(2)])),
                ('party_id', models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(3)])),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField(blank=True, null=True)),
                ('kwh', models.FloatField()),
                ('auth_method', models.CharField(choices=[('AUTH_REQUEST', 'Auth Request'), ('COMMAND', 'Command'), ('WHITELIST', 'Whitelist')], max_length=30)),
                ('authorization_reference', models.CharField(blank=True, max_length=36, null=True)),
                ('connector_id', models.CharField(max_length=36)),
                ('meter_id', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.CharField(max_length=3)),
                ('charging_periods', models.JSONField(default=list)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(max_length=30)),
                ('cdr_token', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cdrs.cdrtoken')),
                ('evse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.chargepoint')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.location')),
            ],
            options={
                'verbose_name': 'Sessions',
                'verbose_name_plural': 'Sessions',
                'ordering': ['-start_date_time'],
            },
        ),
    ]
