# Generated by Django 4.2 on 2023-11-08 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('charge_point', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Текст')),
                ('phone', models.CharField(max_length=256, verbose_name='Телефон')),
                ('email', models.CharField(max_length=256, verbose_name='Email')),
                ('bot_username', models.CharField(max_length=256, verbose_name='Telegram bot')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Vaqt')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='текст')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Наименование')),
                ('icon', models.TextField(null=True, verbose_name='Значок')),
                ('user_defined', models.BooleanField(default=False, verbose_name='Добавлен пользователем')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Текст')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('force_open', models.BooleanField(default=False, verbose_name='Majburiy ochish')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
            },
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('user_defined', models.BooleanField(default=False, verbose_name='Добавлен пользователем')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='car_models', to='vehicle.manufacturer', verbose_name='Производитель')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=100, null=True, verbose_name='VIN')),
                ('state_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Гос.номер')),
                ('type_state_number', models.IntegerField(blank=True, choices=[(1, 'Юридически лицо'), (2, 'Физически лицо')], null=True, verbose_name='Тип гос.номер')),
                ('vehicle_type', models.IntegerField(choices=[(1, 'car'), (2, 'motorbike')], default=1, verbose_name='Тип')),
                ('usable_battery_size', models.FloatField(default=0, verbose_name='Полезный размер батареи')),
                ('release_year', models.CharField(blank=True, max_length=100, null=True, verbose_name='Год выпуска')),
                ('variant', models.CharField(blank=True, max_length=100, null=True, verbose_name='Вариант')),
                ('version', models.CharField(max_length=15, verbose_name='Версия')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удален')),
                ('connector_type', models.ManyToManyField(to='charge_point.connectortype', verbose_name='Тип зарядки')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicle.vehiclemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.user', verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_time', models.DateTimeField(blank=True, null=True, verbose_name='Видимый')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.notification', verbose_name='Уведомление')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пользователь уведомления',
                'verbose_name_plural': 'Уведомления пользователей',
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='users',
            field=models.ManyToManyField(related_name='notifications', through='vehicle.NotificationUser', to='accounts.user'),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Текст')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='news', to='accounts.media', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('icon', models.TextField(null=True, verbose_name='Значок')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.media', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Инструкция',
                'verbose_name_plural': 'Инструкции',
            },
        ),
    ]
