# Generated by Django 4.2 on 2024-03-05 12:52

import apps.core.utils
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tariffs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CdrLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(max_length=45)),
                ('city', models.CharField(max_length=45)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(max_length=3)),
                ('coordinates', models.JSONField()),
                ('evse_id', models.CharField(max_length=48)),
                ('connector_id', models.CharField(max_length=36)),
                ('connector_standard', models.CharField(choices=[('CHADEMO', 'Chademo'), ('CHAOJI', 'Chaoji'), ('DOMESTIC_A', 'Domestic A'), ('DOMESTIC_B', 'Domestic B'), ('DOMESTIC_C', 'Domestic C'), ('DOMESTIC_D', 'Domestic D'), ('DOMESTIC_E', 'Domestic E'), ('DOMESTIC_F', 'Domestic F'), ('DOMESTIC_G', 'Domestic G'), ('DOMESTIC_H', 'Domestic H'), ('DOMESTIC_I', 'Domestic I'), ('DOMESTIC_J', 'Domestic J'), ('DOMESTIC_K', 'Domestic K'), ('DOMESTIC_L', 'Domestic L'), ('DOMESTIC_M', 'Domestic M'), ('DOMESTIC_N', 'Domestic N'), ('DOMESTIC_O', 'Domestic O'), ('GBT_AC', 'Gbt Ac'), ('GBT_DC', 'Gbt Dc'), ('IEC_60309_2_single_16', 'Iec 60309 2 Single 16'), ('IEC_60309_2_three_16', 'Iec 60309 2 Three 16'), ('IEC_60309_2_three_32', 'Iec 60309 2 Three 32'), ('IEC_60309_2_three_64', 'Iec 60309 2 Three 64'), ('IEC_62196_T1', 'Iec 62196 T1'), ('IEC_62196_T1_COMBO', 'Iec 62196 T1 Combo'), ('IEC_62196_T2', 'Iec 62196 T2'), ('IEC_62196_T2_COMBO', 'Iec 62196 T2 Combo'), ('IEC_62196_T3A', 'Iec 62196 T3A'), ('IEC_62196_T3C', 'Iec 62196 T3C'), ('NEMA_5_20', 'Nema 5 20'), ('NEMA_6_30', 'Nema 6 30'), ('NEMA_6_50', 'Nema 6 50'), ('NEMA_10_30', 'Nema 10 30'), ('NEMA_10_50', 'Nema 10 50'), ('NEMA_14_30', 'Nema 14 30'), ('NEMA_14_50', 'Nema 14 50'), ('PANTOGRAPH_BOTTOM_UP', 'Pantograph Bottom Up'), ('PANTOGRAPH_TOP_DOWN', 'Pantograph Top Down'), ('TESLA_R', 'Tesla R'), ('TESLA_S', 'Tesla S')], max_length=50)),
                ('connector_format', models.CharField(choices=[('SOCKET', 'Socket'), ('CABLE', 'Cable')], max_length=50)),
                ('connector_power_type', models.CharField(choices=[('AC_1_PHASE', 'Ac 1 Phase'), ('AC_2_PHASE', 'Ac 2 Phase'), ('AC_2_PHASE_SPLIT', 'Ac 2 Phase Split'), ('AC_3_PHASE', 'Ac 3 Phase'), ('DC', 'Dc')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CdrToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=2)),
                ('party_id', models.CharField(max_length=3)),
                ('uid', models.CharField(max_length=36)),
                ('type', models.CharField(choices=[('AD_HOC_USER', 'Ad Hoc User'), ('APP_USER', 'App User'), ('OTHER', 'Other'), ('RFID', 'Rfid')], max_length=50)),
                ('contract_id', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='ChargingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date_time', models.DateTimeField()),
                ('tariff_id', models.CharField(blank=True, max_length=36, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SignedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('encoding_method', models.CharField(max_length=36)),
                ('encoding_method_version', models.IntegerField(blank=True, null=True)),
                ('public_key', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(512)])),
                ('url', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(512)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SignedValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('nature', models.CharField(max_length=32)),
                ('plain_data', models.TextField(max_length=512)),
                ('signed_data', models.TextField(max_length=5000)),
                ('signed_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdrs.signeddata')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CdrDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CURRENT', 'Current'), ('ENERGY', 'Energy'), ('ENERGY_EXPORT', 'Energy Export'), ('ENERGY_IMPORT', 'Energy Import'), ('MAX_CURRENT', 'Max Current'), ('MIN_CURRENT', 'Min Current'), ('MAX_POWER', 'Max Power'), ('MIN_POWER', 'Min Power'), ('PARKING_TIME', 'Parking Time'), ('POWER', 'Power'), ('RESERVATION_TIME', 'Reservation Time'), ('STATE_OF_CHARGE', 'State Of Charge'), ('TIME', 'Time')], max_length=20)),
                ('volume', models.FloatField()),
                ('charging_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='cdrs.chargingperiod')),
            ],
        ),
        migrations.CreateModel(
            name='Cdr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=2)),
                ('party_id', models.CharField(max_length=3)),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('session_id', models.CharField(blank=True, max_length=36, null=True)),
                ('auth_method', models.CharField(max_length=20)),
                ('authorization_reference', models.CharField(blank=True, max_length=36, null=True)),
                ('meter_id', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.CharField(max_length=3)),
                ('total_cost', models.JSONField(default=apps.core.utils.price_default_value)),
                ('total_fixed_cost', models.JSONField(default=apps.core.utils.price_default_value)),
                ('total_energy', models.FloatField()),
                ('total_energy_cost', models.JSONField(default=apps.core.utils.price_default_value)),
                ('total_time', models.FloatField()),
                ('total_time_cost', models.JSONField(default=apps.core.utils.price_default_value)),
                ('total_parking_time', models.FloatField(blank=True, null=True)),
                ('total_parking_cost', models.JSONField(default=apps.core.utils.price_default_value)),
                ('total_reservation_cost', models.JSONField(default=apps.core.utils.price_default_value)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_reference_id', models.CharField(blank=True, max_length=39, null=True)),
                ('credit', models.BooleanField(blank=True, null=True)),
                ('credit_reference_id', models.CharField(blank=True, max_length=39, null=True)),
                ('home_charging_compensation', models.BooleanField(blank=True, null=True)),
                ('last_updated', models.DateTimeField()),
                ('cdr_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdrs.cdrlocation')),
                ('cdr_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdrs.cdrtoken')),
                ('signed_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cdrs.signeddata')),
                ('tariffs', models.ManyToManyField(blank=True, to='tariffs.tariff')),
            ],
        ),
    ]
