# Generated by Django 4.2 on 2024-03-04 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('website', models.URLField(max_length=255, verbose_name='Website')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.image', verbose_name='Logo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('token', models.CharField(max_length=64)),
                ('url', models.URLField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CredentialsRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('role', models.CharField(choices=[('CPO', 'Cpo'), ('EMSP', 'Emsp'), ('HUB', 'Hub'), ('NAP', 'Nap'), ('NSP', 'Nsp'), ('OTHER', 'Other'), ('SCSP', 'Scsp')], max_length=10, verbose_name='Role')),
                ('party_id', models.CharField(max_length=3, verbose_name='Party id')),
                ('country_code', models.CharField(max_length=2, verbose_name='Country code')),
                ('business_details', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='credentials.businessdetails')),
                ('credentials', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='credentials.credentials')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
