# Generated by Django 4.2 on 2024-03-04 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_alter_businessdetails_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credentialsrole',
            options={'ordering': ('-updated_at',), 'verbose_name': 'Credentials Role', 'verbose_name_plural': 'Credentials Roles'},
        ),
    ]
