# Generated by Django 4.2 on 2024-03-04 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0003_alter_credentialsrole_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentialsrole',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='credentialsrole',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='credentialsrole',
            name='credentials',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roles', to='credentials.credentials'),
        ),
    ]
