# Generated by Django 4.2 on 2024-03-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('image', models.ImageField(upload_to='%Y/%m/%d', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
            },
        ),
        migrations.CreateModel(
            name='MinBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Min Balance',
                'verbose_name_plural': 'Min Balances',
            },
        ),
        migrations.CreateModel(
            name='QrCodeScanerCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('count', models.IntegerField(blank=True, null=True, verbose_name='Сканлаган QR кодлар сони')),
                ('iphone', models.IntegerField(default=0, verbose_name='Iphone')),
                ('android', models.IntegerField(default=0, verbose_name='Android')),
                ('last_scan', models.DateTimeField(auto_now=True, verbose_name='Сканлаган сана')),
            ],
            options={
                'verbose_name': 'QR кодлар сони',
                'verbose_name_plural': 'QR кодлар сони',
            },
        ),
    ]
