# Generated by Django 4.2 on 2024-03-04 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_country_district_region_delete_media_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='country',
            new_name='region',
        ),
    ]
