# Generated by Django 4.2 on 2024-03-04 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_country_district_region'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['-name'], 'verbose_name': 'District', 'verbose_name_plural': 'District'},
        ),
    ]
