# Generated by Django 4.2 on 2024-03-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_district_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('url', models.URLField(max_length=255, verbose_name='Url')),
                ('thumbnail', models.URLField(blank=True, max_length=255, null=True, verbose_name='Thumbnail')),
                ('category', models.CharField(choices=[('CHARGER', 'Charger'), ('ENTRANCE', 'Entrance'), ('LOCATION', 'Location'), ('NETWORK', 'Network'), ('OPERATOR', 'Operator'), ('OTHER', 'Other'), ('OWNER', 'Owner')], max_length=20, verbose_name='Category')),
                ('type', models.CharField(max_length=4, verbose_name='Image Extension')),
                ('width', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Width')),
                ('height', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Height')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
