# Generated by Django 4.2 on 2024-03-04 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connector',
            options={'ordering': ['id'], 'verbose_name': 'Connector', 'verbose_name_plural': 'Connector'},
        ),
    ]
