# Generated by Django 4.2 on 2024-03-05 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_connector_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChargePointError',
        ),
    ]
