# Generated by Django 4.2 on 2024-03-01 11:27

import apps.tariff.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('type', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vat', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('step_size', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TariffRestrictions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('start_time', models.CharField(blank=True, max_length=5, null=True)),
                ('end_time', models.CharField(blank=True, max_length=5, null=True)),
                ('start_date', models.CharField(blank=True, max_length=10, null=True)),
                ('end_date', models.CharField(blank=True, max_length=10, null=True)),
                ('min_kwh', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_kwh', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_current', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_current', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_power', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_power', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_duration', models.IntegerField(blank=True, null=True)),
                ('max_duration', models.IntegerField(blank=True, null=True)),
                ('day_of_week', models.JSONField(default=list)),
                ('reservation', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TariffElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('price_components', models.ManyToManyField(to='tariff.pricecomponent')),
                ('restrictions', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tariff.tariffrestrictions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('currency', models.CharField(max_length=3, verbose_name='ISO-4217 code of the currency of this tariff.')),
                ('type', models.CharField(blank=True, choices=[('AD_HOC_PAYMENT', 'Ad Hoc Payment'), ('PROFILE_CHEAP', 'Profile Cheap'), ('PROFILE_FAST', 'Profile Fast'), ('PROFILE_GREEN', 'Profile Green'), ('REGULAR', 'Regular')], max_length=50, null=True)),
                ('tariff_alt_url', models.URLField(blank=True, null=True)),
                ('tariff_alt_text', models.JSONField(default=apps.tariff.models.tariff_alt_text_default)),
                ('min_price', models.JSONField(default=apps.tariff.models.price_default)),
                ('max_price', models.JSONField(default=apps.tariff.models.price_default)),
                ('start_date_time', models.DateTimeField(blank=True, null=True)),
                ('end_date_time', models.DateTimeField(blank=True, null=True)),
                ('energy_mix', models.JSONField(blank=True, null=True)),
                ('last_updated', models.DateTimeField()),
                ('elements', models.ManyToManyField(to='tariff.tariffelement')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
