# Generated by Django 4.2 on 2023-11-08 23:40

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Min Balance',
                'verbose_name_plural': 'Min Balances',
            },
        ),
        migrations.CreateModel(
            name='PaymentMerchantRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('provider', models.CharField(choices=[('payme', 'Payme'), ('click', 'Click'), ('paylov', 'Paylov'), ('uzum_bank', 'Uzum Bank'), ('card', 'Card')], max_length=63, verbose_name='Provider')),
                ('header', models.TextField(verbose_name='Header')),
                ('body', models.TextField(verbose_name='Body')),
                ('method', models.CharField(max_length=32, verbose_name='Method')),
                ('response', models.TextField(blank=True, null=True)),
                ('response_status_code', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Payment Merchant Request Log',
                'verbose_name_plural': 'Payment Merchant Request Logs',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for confirmation'), ('preauth', 'Pre-authorized'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('refunded', 'Refunded'), ('error', 'Error'), ('input', 'Input')], default='waiting', max_length=10)),
                ('fraud_status', models.CharField(choices=[('unknown', 'Unknown'), ('accept', 'Passed'), ('reject', 'Rejected'), ('review', 'Review')], default='unknown', max_length=10, verbose_name='fraud check')),
                ('fraud_message', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255)),
                ('currency', models.CharField(max_length=10)),
                ('total', models.DecimalField(decimal_places=2, default='0.0', max_digits=9)),
                ('delivery', models.DecimalField(decimal_places=2, default='0.0', max_digits=9)),
                ('tax', models.DecimalField(decimal_places=2, default='0.0', max_digits=9)),
                ('description', models.TextField(blank=True, default='')),
                ('billing_first_name', models.CharField(blank=True, max_length=256)),
                ('billing_last_name', models.CharField(blank=True, max_length=256)),
                ('billing_address_1', models.CharField(blank=True, max_length=256)),
                ('billing_address_2', models.CharField(blank=True, max_length=256)),
                ('billing_city', models.CharField(blank=True, max_length=256)),
                ('billing_postcode', models.CharField(blank=True, max_length=256)),
                ('billing_country_code', models.CharField(blank=True, max_length=2)),
                ('billing_country_area', models.CharField(blank=True, max_length=256)),
                ('billing_email', models.EmailField(blank=True, max_length=254)),
                ('billing_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('customer_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('extra_data', models.TextField(blank=True, default='')),
                ('message', models.TextField(blank=True, default='')),
                ('token', models.CharField(blank=True, default='', max_length=36)),
                ('captured_amount', models.DecimalField(decimal_places=2, default='0.0', max_digits=9)),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Paid At')),
                ('cancel_time', models.DateTimeField(blank=True, null=True, verbose_name='Cancel Time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='accounts.user')),
            ],
            options={
                'abstract': False,
                'unique_together': {('variant', 'transaction_id')},
            },
        ),
        migrations.CreateModel(
            name='UserPaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок')),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Vaqt')),
            ],
            options={
                'verbose_name': 'Статус платежа',
                'verbose_name_plural': 'Статусы платежа',
            },
        ),
        migrations.CreateModel(
            name='UserBalanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Summa')),
                ('operation', models.IntegerField(choices=[(1, "Hisob to'ldirildi"), (2, 'Hisob raqamidan pul yechib olindi')], verbose_name='Bajarilgan amal')),
                ('prev_balance', models.FloatField(verbose_name="O'zgarishdan oldingi balans")),
                ('new_balance', models.FloatField(verbose_name="O'zgarishdan keyingi balans")),
                ('comment', models.TextField(blank=True, null=True, verbose_name="Qo'shimcha ma'lumot")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vaqt')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('connector_id', models.IntegerField(blank=True, null=True, verbose_name='Connector id')),
                ('charge_transaction_id', models.IntegerField(blank=True, null=True, verbose_name='Charge transaction id')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payment.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.user', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi hisobi tarixi',
                'verbose_name_plural': 'Foydalanuvchi hisobi tarixlari',
            },
        ),
        migrations.CreateModel(
            name='DiscountUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_user', to='accounts.user')),
            ],
            options={
                'verbose_name': 'Discount User',
                'verbose_name_plural': 'Discount Users',
            },
        ),
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('card_number', models.CharField(max_length=255, verbose_name='Card Number')),
                ('expire_date', models.CharField(max_length=255, verbose_name='Expire Date')),
                ('card_id', models.CharField(max_length=255, verbose_name='Card ID')),
                ('token', models.CharField(max_length=255, null=True, verbose_name='Token')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Confirmed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user', verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Card',
                'verbose_name_plural': 'User Cards',
                'unique_together': {('user', 'card_number')},
            },
        ),
    ]
